---
id: nginx-tech-talks
base_name: ngx-http-groonga
tags:
- rabbit
- nginx
- groonga
presentation_date: 2016-02-08
version: 2016.2.8.0
licenses:
- CC BY 3.0
- CC BY-SA 4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: 
